{% set name = "lazydocker" %}
{% set version = "0.24.1" %}
{% set author = "jesseduffield" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ author }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f54197d333a28e658d2eb4d9b22461ae73721ec9e4106ba23ed177fc530c21f4

build:
  number: 1

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - lazydocker --version  # [unix]
    - lazydocker.exe --version  # [win]

about:
  home: https://github.com/{{ author }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: "The lazier way to manage everything docker"
  description: |
    The lazier way to manage everything docker.
  dev_url: https://github.com/{{ author }}/{{ name }}

extra:
  recipe-maintainers:
    - anjos
    - eunos-1128
